name: Build localization
on:
  push:
jobs:
  localizator:
    name: Build language resourses
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
      - name: Build UNDEFs, json and js files
        run: cd BSB_LAN/localization && ./create-undefs.pl && cd ..
      - name: Copy files to repo
        uses: test-room-7/action-update-file@v1
        with:
           file-path: |
             BSB_LAN/localization/json/*.json
             BSB_LAN/localization/www/*.*
             BSB_LAN/localization/UNDEF_LANG_*.h
             BSB_LAN/localization/LANG_C.h
           commit-msg: Update language resources
           github-token: ${{ secrets.GITHUB_TOKEN }}
           
